### ISSUE TITLE
bug: lifeの計算がおかしそう

### ISSUE THREAD

**Issue by orisano** [higumachan/duelmanager#1]
https://github.com/higumachan/duelmanager/blob/master/src/store/life/index.js#L26
returnがないので常にundefinedが返ってそう

**Comment by higumachan** [comment]
次のPRで直ってます

**Comment by amanoese** [comment]
私も見つけました

**Comment by higumachan** [comment]
JSのラムダ式を勘違いしていた。

**Comment by higumachan** [comment]
#4 で修正しました
